const KEY='family-trips-alpha-0.1';
const cats={flight:['✈️','טיסות'],hotel:['🏨','מלונות'],transport:['🚗','תחבורה'],activity:['🎟️','אטרקציות'],restaurant:['🍽️','מסעדות'],insurance:['🛡️','ביטוח'],document:['📄','מסמכים'],contact:['☎️','אנשי קשר']};
let s=load();
function load(){try{return {...{trip:null,items:[],docs:[],view:'today',category:null,itemId:null,modal:null,toast:null},...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return {trip:null,items:[],docs:[],view:'today',category:null,itemId:null,modal:null,toast:null}}}
function save(){localStorage.setItem(KEY,JSON.stringify({trip:s.trip,items:s.items,docs:s.docs}))}
const uid=p=>`${p}-${Date.now()}-${Math.random().toString(16).slice(2)}`;
const esc=v=>String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>v?new Intl.DateTimeFormat('he-IL',{day:'numeric',month:'short',year:'numeric',hour:v.includes('T')?'2-digit':undefined,minute:v.includes('T')?'2-digit':undefined}).format(new Date(v.includes('T')?v:`${v}T12:00:00`)):'ללא תאריך';
function status(){if(!s.trip)return'Empty';if(!s.trip.startDate||!s.trip.endDate)return'Draft';let n=new Date(),a=new Date(s.trip.startDate),b=new Date(`${s.trip.endDate}T23:59:59`);return n<a?'Planned':n>b?'Completed':'Active'}
function ensureTrip(){if(!s.trip)s.trip={id:uid('trip'),name:'הטיול המשפחתי שלי',startDate:'',endDate:'',createdAt:new Date().toISOString()}}
function route(view,o={}){s.view=view;s.category=o.category||null;s.itemId=o.itemId||null;render();scrollTo(0,0)}
function flash(t){s.toast=t;render();setTimeout(()=>{if(s.toast===t){s.toast=null;render()}},1800)}
function conflicts(){if(!s.trip?.startDate||!s.trip?.endDate){s.items=s.items.map(x=>({...x,conflict:false}));return}let a=new Date(s.trip.startDate),b=new Date(`${s.trip.endDate}T23:59:59`);s.items=s.items.map(x=>({...x,conflict:x.startAt?(new Date(x.startAt)<a||new Date(x.startAt)>b):false}))}
function itemRow(x){return `<button class="item ${x.conflict?'conflict':''}" data-route="detail" data-id="${x.id}"><span><b>${cats[x.type]?.[0]||'📌'} ${esc(x.title)}</b><small class="muted">${fmt(x.startAt)}</small></span><span class="badge ${x.conflict?'warn':''}">${x.conflict?'דורש בדיקה':cats[x.type]?.[1]||x.type}</span></button>`}
function empty(){return `<section class="card empty hero"><div class="icon">🧭</div><h2>מתחילים מטיול ריק</h2><p class="muted">העלה מסמך או צור פריט ראשון. הטיול ייווצר רק לאחר שמירה.</p><div class="actions" style="justify-content:center"><button class="btn" data-act="upload">העלאת מסמך</button><button class="btn secondary" data-act="add">יצירת פריט</button></div></section>`}
function today(){if(!s.trip)return empty();let up=[...s.items].filter(x=>x.startAt).sort((a,b)=>new Date(a.startAt)-new Date(b.startAt)).slice(0,3);return `<section class="card hero"><h2>מרכז הטיול</h2><p class="muted">מה שחשוב עכשיו או בקרוב.</p>${up.map(itemRow).join('')||'<p class="muted">אין עדיין אירועים מתוארכים.</p>'}</section><section class="card"><h2>גישה מהירה</h2><div class="grid two">${['insurance','hotel','activity','document'].map(k=>`<button class="quick" data-route="center" data-cat="${k}"><span>${cats[k][0]}</span><b>${cats[k][1]}</b><small class="muted">${s.items.filter(x=>x.type===k).length+(k==='document'?s.docs.length:0)} פריטים</small></button>`).join('')}</div></section>`}
function timeline(){if(!s.trip)return empty();let d=[...s.items].filter(x=>x.startAt).sort((a,b)=>new Date(a.startAt)-new Date(b.startAt));return `<section class="card"><h2>Timeline</h2><div class="timeline">${d.map(itemRow).join('')||'<p class="muted">ה־Timeline ייבנה מפריטים עם תאריך.</p>'}</div></section>`}
function center(){if(!s.trip)return empty();if(s.category){let k=s.category,items=s.items.filter(x=>x.type===k);return `<section class="card"><button class="btn ghost" data-route="center">חזרה לקטגוריות</button><h2>${cats[k][0]} ${cats[k][1]}</h2><div class="list">${items.map(itemRow).join('')}${k==='document'?s.docs.map(d=>`<div class="item"><span><b>📄 ${esc(d.name)}</b><small class="muted">${esc(d.type||'קובץ')} · ${Math.round(d.size/1024)}KB</small></span><span class="badge">נקלט</span></div>`).join(''):''}</div>${!items.length&&!(k==='document'&&s.docs.length)?'<p class="muted">אין פריטים.</p>':''}</section>`}return `<section class="card"><h2>Trip Center</h2><p class="muted">ניהול מידע לפי קטגוריות. Search משני.</p><div class="grid two">${Object.entries(cats).map(([k,v])=>`<button class="quick" data-route="center" data-cat="${k}"><span>${v[0]}</span><b>${v[1]}</b><small class="muted">${s.items.filter(x=>x.type===k).length+(k==='document'?s.docs.length:0)} פריטים</small></button>`).join('')}</div></section>`}
function settings(){if(!s.trip)return empty();return `<section class="card"><h2>הגדרות טיול</h2><form id="tripForm"><div class="field"><label>שם</label><input name="name" value="${esc(s.trip.name)}"></div><div class="grid two"><div class="field"><label>התחלה</label><input type="date" name="startDate" value="${s.trip.startDate}"></div><div class="field"><label>סיום</label><input type="date" name="endDate" value="${s.trip.endDate}"></div></div><p class="hint">אפשר להוסיף, לשנות או להסיר תאריכים. פריטים קשיחים אינם מוזזים אוטומטית.</p><div class="actions"><button class="btn">שמירה</button><button type="button" class="btn danger" data-act="reset">איפוס מקומי</button></div></form></section>`}
function detail(){let x=s.items.find(i=>i.id===s.itemId);if(!x)return '<section class="card">הפריט לא נמצא.</section>';return `<section class="card ${x.conflict?'conflict':''}"><button class="btn ghost" data-route="center" data-cat="${x.type}">חזרה</button><h2>${cats[x.type]?.[0]||'📌'} ${esc(x.title)}</h2><p><b>מועד:</b> ${fmt(x.startAt)}</p>${x.location?`<p><b>מיקום:</b> ${esc(x.location)}</p>`:''}${x.notes?`<p>${esc(x.notes)}</p>`:''}${x.conflict?'<p style="color:#8a4b08;font-weight:800">מחוץ לטווח הטיול. התאריך לא שונה אוטומטית.</p>':''}<div class="actions"><button class="btn secondary" data-act="edit" data-id="${x.id}">עריכה</button>${x.location?`<a class="btn" target="_blank" rel="noopener" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(x.location)}">מפה</a>`:''}<button class="btn danger" data-act="delete" data-id="${x.id}">מחיקה</button></div></section>`}
function modal(){if(!s.modal)return'';if(s.modal==='upload')return `<div class="modal-bg"><section class="modal"><div class="modal-head"><h2>קליטת מסמך</h2><button class="close" data-act="close">✕</button></div><form id="uploadForm"><div class="field"><label>PDF או תמונה</label><input type="file" name="files" accept="application/pdf,image/*" multiple required><span class="hint">באלפא זו נשמרת מטא־דאטה בלבד; OCR עדיין לא ממומש.</span></div><button class="btn">קליטה</button></form></section></div>`;let x=s.modal.id?s.items.find(i=>i.id===s.modal.id):{type:'hotel',title:'',startAt:'',location:'',notes:''};return `<div class="modal-bg"><section class="modal"><div class="modal-head"><h2>${s.modal.id?'עריכת פריט':'יצירת פריט'}</h2><button class="close" data-act="close">✕</button></div><form id="itemForm" data-id="${s.modal.id||''}"><div class="field"><label>סוג</label><select name="type">${Object.entries(cats).filter(([k])=>k!=='document').map(([k,v])=>`<option value="${k}" ${x.type===k?'selected':''}>${v[0]} ${v[1]}</option>`).join('')}</select></div><div class="field"><label>כותרת</label><input name="title" required value="${esc(x.title)}"></div><div class="field"><label>מועד</label><input type="datetime-local" name="startAt" value="${x.startAt||''}"></div><div class="field"><label>מיקום</label><input name="location" value="${esc(x.location)}"></div><div class="field"><label>הערות</label><textarea name="notes">${esc(x.notes)}</textarea></div><button class="btn">שמירה</button></form></section></div>`}
function nav(v,i,l){return `<button class="nav ${s.view===v||(v==='center'&&s.view==='detail')?'active':''}" data-route="${v}">${i}<br>${l}</button>`}
function render(){let body=s.view==='today'?today():s.view==='timeline'?timeline():s.view==='center'?center():s.view==='settings'?settings():detail();document.querySelector('#app').innerHTML=`<div class="shell">${navigator.onLine?'':'<div class="offline">מצב אופליין</div>'}<header class="header"><div class="header-row"><div><h1>${esc(s.trip?.name||'Family Trips')}</h1><p>${s.trip?(s.trip.startDate?`${fmt(s.trip.startDate)} — ${fmt(s.trip.endDate)}`:'תאריכים עדיין לא הוגדרו'):'הטיול מתחיל במסמך או בפריט הראשון'}</p></div><span class="pill">${status()}</span></div></header><main>${body}</main><button class="fab" data-act="add">+</button><nav class="bottom">${nav('today','🏠','Today')}${nav('timeline','🗓️','Timeline')}${nav('center','🗂️','Trip Center')}${nav('settings','⚙️','הגדרות')}</nav>${modal()}${s.toast?`<div class="toast">${esc(s.toast)}</div>`:''}</div>`}
document.addEventListener('click',e=>{let r=e.target.closest('[data-route]');if(r){route(r.dataset.route,{category:r.dataset.cat,itemId:r.dataset.id});return}let a=e.target.closest('[data-act]');if(!a)return;let x=a.dataset.act;if(x==='add'){s.modal={};render()}if(x==='upload'){s.modal='upload';render()}if(x==='close'){s.modal=null;render()}if(x==='edit'){s.modal={id:a.dataset.id};render()}if(x==='delete'&&confirm('למחוק?')){s.items=s.items.filter(i=>i.id!==a.dataset.id);save();route('center');flash('הפריט נמחק')}if(x==='reset'&&confirm('למחוק את כל הנתונים המקומיים?')){localStorage.removeItem(KEY);s=load();render()}});
document.addEventListener('submit',e=>{e.preventDefault();let f=new FormData(e.target);if(e.target.id==='itemForm'){ensureTrip();let id=e.target.dataset.id||uid('item'),old=s.items.find(i=>i.id===id)||{};let x={...old,id,type:f.get('type'),title:String(f.get('title')).trim(),startAt:f.get('startAt')||'',location:String(f.get('location')||'').trim(),notes:String(f.get('notes')||'').trim(),origin:'Manual'};s.items=e.target.dataset.id?s.items.map(i=>i.id===id?x:i):[...s.items,x];conflicts();save();s.modal=null;route('detail',{itemId:id});flash('נשמר')}if(e.target.id==='uploadForm'){let files=[...e.target.elements.files.files];ensureTrip();files.forEach(file=>s.docs.push({id:uid('doc'),name:file.name,type:file.type,size:file.size,origin:'Upload'}));save();s.modal=null;route('center',{category:'document'});flash(`${files.length} מסמכים נקלטו`)}if(e.target.id==='tripForm'){let a=f.get('startDate')||'',b=f.get('endDate')||'';if(a&&b&&a>b)return alert('תאריך הסיום חייב להיות אחרי ההתחלה');s.trip={...s.trip,name:String(f.get('name')||'').trim()||'הטיול המשפחתי שלי',startDate:a,endDate:b};conflicts();save();render();flash('תאריכי הטיול נשמרו')}});
addEventListener('online',render);addEventListener('offline',render);if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js'));render();
