import { ITEM_TYPES, createSuggestion, findPossibleDuplicates, suggestionToItem, validateSource } from './ingestion.js';
import './v4.css';

const KEY='family-trips-alpha-0.2';
const EMPTY={trip:null,items:[],sources:[],suggestions:[],packing:[],view:'today',category:null,itemId:null,suggestionId:null,modal:null,timelineMode:'all',calendarDate:null,toast:null};
let state=load();

function clone(value){return JSON.parse(JSON.stringify(value))}
function load(){
  try {
    const stored=JSON.parse(localStorage.getItem(KEY)||'{}');
    return {...clone(EMPTY),...stored,suggestions:stored.suggestions||[],view:'today',modal:null,toast:null};
  } catch { return clone(EMPTY); }
}
function save(){localStorage.setItem(KEY,JSON.stringify({trip:state.trip,items:state.items,sources:state.sources,suggestions:state.suggestions,packing:state.packing}))}
function uid(prefix='id'){return `${prefix}-${Date.now()}-${Math.random().toString(16).slice(2)}`}
function esc(value=''){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function dateOnly(value){return value?String(value).slice(0,10):''}
function today(){return new Date().toISOString().slice(0,10)}
function fmt(value,withTime=true){if(!value)return 'ללא תאריך';const d=new Date(value.length===10?`${value}T12:00:00`:value);return new Intl.DateTimeFormat('he-IL',withTime?{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}:{day:'numeric',month:'short',year:'numeric'}).format(d)}
function ensureTrip(seed={}){if(state.trip)return;state.trip={id:uid('trip'),name:seed.name||'הטיול המשפחתי שלי',startDate:'',endDate:'',createdAt:new Date().toISOString()};if(!state.packing.length)state.packing=defaultPacking()}
function defaultPacking(){return [{id:uid('pl'),name:'מסמכים וכסף',items:[['דרכונים',true],['ביטוח נסיעות',true],['כרטיסי אשראי',true]].map(([name,suggested])=>({id:uid('pi'),name,done:false,suggested}))}]}
function route(view,options={}){state.view=view;state.category=options.category||null;state.itemId=options.itemId||null;state.suggestionId=options.suggestionId||null;render();scrollTo(0,0)}
function notify(text){state.toast=text;render();setTimeout(()=>{if(state.toast===text){state.toast=null;render()}},2400)}
function status(){if(!state.trip)return 'Empty';if(state.trip.startDate&&state.trip.endDate){const now=new Date(),start=new Date(`${state.trip.startDate}T00:00:00`),end=new Date(`${state.trip.endDate}T23:59:59`);if(now>=start&&now<=end)return 'Active';if(now>end)return 'Completed';return 'Planned'}return 'Draft'}
function conflict(item){if(!state.trip?.startDate||!state.trip?.endDate||['entire','none'].includes(item.schedule)||!item.startAt)return false;const d=new Date(item.startAt),a=new Date(`${state.trip.startDate}T00:00:00`),b=new Date(`${state.trip.endDate}T23:59:59`);return d<a||d>b}
function sourceById(id){return state.sources.find(source=>source.id===id)}
function suggestionById(id){return state.suggestions.find(suggestion=>suggestion.id===id)}

function header(){return `<header class="top"><div class="top-in"><div class="brand"><img src="assets/icons/icon-192.png" alt=""><div><h1>${esc(state.trip?.name||'Family Trips')}</h1><p>${state.trip?(state.trip.startDate?`${fmt(state.trip.startDate,false)} — ${state.trip.endDate?fmt(state.trip.endDate,false):'ללא סיום'}`:'הטיול נבנה מהמידע שאישרת'):'מקור ראשון ייצור טיול והצעה לבדיקה'}</p></div></div><span class="status">${status()}</span></div></header>`}
function empty(){return `<section class="card hero empty"><div class="big">🧭</div><h2>מתחילים מטיול ריק</h2><p class="muted">העלה PDF או תמונה, צלם, הדבק קישור או הזן פריט ידנית.</p><div class="actions" style="justify-content:center"><button class="btn" data-action="create">הוספת מקור או פריט</button></div></section>`}
function itemRow(item){return `<button class="row ${conflict(item)?'conflict':''}" data-route="detail" data-id="${item.id}"><span class="row-main"><b>${ITEM_TYPES[item.type]?.icon||'📌'} ${esc(item.title)}</b><small class="muted">${item.provider?`${esc(item.provider)} · `:''}${item.schedule==='entire'?'לכל הטיול':item.schedule==='none'?'ללא תאריך':item.schedule==='range'?`${fmt(item.startAt)} — ${fmt(item.endAt)}`:fmt(item.startAt)}</small></span>${conflict(item)?'<span class="badge warn">מחוץ לטווח</span>':`<span class="badge">${ITEM_TYPES[item.type]?.label||item.type}</span>`}</button>`}
function suggestionRow(suggestion){const source=sourceById(suggestion.sourceId);return `<button class="row suggestion-row" data-route="suggestion" data-id="${suggestion.id}"><span class="row-main"><b>✨ ${esc(suggestion.proposed.title)}</b><small class="muted">${esc(source?.name||source?.url||'מקור')} · ביטחון ${confidenceLabel(suggestion.confidence)}</small></span><span class="badge ${suggestion.status==='pending'?'warn':'blue'}">${suggestionStatus(suggestion.status)}</span></button>`}
function confidenceLabel(value){return ({high:'גבוה',medium:'בינוני',low:'נמוך'})[value]||value}
function suggestionStatus(value){return ({pending:'ממתין לאישור',deferred:'נדחה לאחר כך',rejected:'נדחה',approved:'אושר'})[value]||value}

function todayView(){if(!state.trip)return empty();const dated=[...state.items].filter(i=>!['none','entire'].includes(i.schedule)&&i.startAt).sort((a,b)=>new Date(a.startAt)-new Date(b.startAt));const todayItems=dated.filter(i=>dateOnly(i.startAt)===today());const next=dated.find(i=>new Date(i.startAt)>new Date());const shown=[...todayItems];if(next&&!shown.some(i=>i.id===next.id))shown.push(next);const pending=state.suggestions.filter(s=>['pending','deferred'].includes(s.status));return `<section class="card hero"><h2>Today</h2><p class="muted">מה שרלוונטי עכשיו והאירוע הבא.</p><div class="list">${shown.length?shown.map(itemRow).join(''):'<div class="empty compact"><p class="muted">אין אירועים להיום.</p></div>'}</div></section>${pending.length?`<section class="card"><div class="section-head"><h3>הצעות שממתינות לבדיקה</h3><span class="badge warn">${pending.length}</span></div><div class="list">${pending.map(suggestionRow).join('')}</div></section>`:''}`}
function timeline(){if(!state.trip)return empty();let items=[...state.items].filter(i=>!['none','entire'].includes(i.schedule)&&i.startAt).sort((a,b)=>new Date(a.startAt)-new Date(b.startAt));if(state.timelineMode==='day')items=items.filter(i=>dateOnly(i.startAt)===today());const groups={};for(const item of items)(groups[dateOnly(item.startAt)]??=[]).push(item);return `<section class="card"><h2>Timeline</h2><div class="tabs">${[['all','כל הטיול'],['day','היום']].map(([key,label])=>`<button class="${state.timelineMode===key?'active':''}" data-action="timeline-mode" data-mode="${key}">${label}</button>`).join('')}</div>${Object.keys(groups).length?Object.entries(groups).map(([date,group])=>`<div class="day-group"><div class="day-head">${fmt(date,false)}</div><div class="list">${group.map(itemRow).join('')}</div></div>`).join(''):'<div class="empty"><p class="muted">אין אירועים בתצוגה.</p></div>'}</section>`}
function calendar(){if(!state.trip)return empty();const selected=state.calendarDate||state.trip.startDate||today();const base=new Date(`${selected}T12:00:00`),year=base.getFullYear(),month=base.getMonth(),first=new Date(year,month,1),last=new Date(year,month+1,0);const cells=[];for(let i=0;i<first.getDay();i++)cells.push('<div></div>');for(let day=1;day<=last.getDate();day++){const key=`${year}-${String(month+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`,count=state.items.filter(i=>dateOnly(i.startAt)===key).length,inTrip=state.trip.startDate&&state.trip.endDate&&key>=state.trip.startDate&&key<=state.trip.endDate;cells.push(`<button class="cal-cell ${inTrip?'in-trip':''} ${key===selected?'selected':''}" data-action="calendar-date" data-date="${key}"><b>${day}</b><div>${Array.from({length:Math.min(count,4)},()=>'<span class="cal-dot"></span>').join('')}</div></button>`)}const items=state.items.filter(i=>dateOnly(i.startAt)===selected);return `<section class="card"><h2>Calendar</h2><p class="muted">${new Intl.DateTimeFormat('he-IL',{month:'long',year:'numeric'}).format(base)}</p><div class="calendar">${['א','ב','ג','ד','ה','ו','ש'].map(x=>`<b style="text-align:center">${x}</b>`).join('')}${cells.join('')}</div></section><section class="card"><h3>${fmt(selected,false)}</h3><div class="list">${items.length?items.map(itemRow).join(''):'<div class="empty compact"><p class="muted">אין אירועים בתאריך שנבחר.</p></div>'}</div></section>`}
function center(){if(!state.trip)return empty();if(state.category){const items=state.items.filter(i=>i.type===state.category);const sources=state.category==='document'?state.sources:[];const suggestions=state.category==='document'?state.suggestions.filter(s=>s.status!=='approved'):[];return `<section class="card"><button class="btn ghost" data-route="center">חזרה</button><h2>${ITEM_TYPES[state.category]?.icon||'📌'} ${ITEM_TYPES[state.category]?.label||''}</h2>${suggestions.length?`<h3>הצעות</h3><div class="list">${suggestions.map(suggestionRow).join('')}</div>`:''}${items.length?`<h3>פריטים</h3><div class="list">${items.map(itemRow).join('')}</div>`:''}${sources.length?`<h3>מקורות</h3><div class="list">${sources.map(sourceRow).join('')}</div>`:''}${!items.length&&!sources.length&&!suggestions.length?'<div class="empty"><p class="muted">אין פריטים.</p></div>':''}<div class="actions"><button class="btn" data-action="create">הוספה</button></div></section>`}return `<section class="card"><h2>Trip Center</h2><p class="muted">ניהול מידע, מקורות והצעות.</p><div class="grid two">${Object.entries(ITEM_TYPES).map(([key,type])=>`<button class="tile" data-route="center" data-cat="${key}"><span class="ico">${type.icon}</span><b>${type.label}</b><small class="muted">${state.items.filter(i=>i.type===key).length+(key==='document'?state.sources.length:0)} פריטים</small></button>`).join('')}<button class="tile" data-route="packing"><span class="ico">🧳</span><b>ציוד</b><small class="muted">${state.packing.length} רשימות</small></button></div></section>`}
function sourceRow(source){return `<div class="row"><span class="row-main"><b>📎 ${esc(source.name||source.url)}</b><small class="muted">${esc(source.kind)} · ${esc(source.status)}</small></span>${source.kind==='link'?`<a class="btn ghost" href="${esc(source.url)}" target="_blank" rel="noopener">פתיחה</a>`:'<button class="btn ghost" data-action="open-source" data-id="'+source.id+'">פתיחה</button>'}</div>`}

function packing(){if(!state.trip)return empty();return `<section class="card"><div class="section-head"><div><h2>Packing Lists</h2><p class="muted small">הרשימות הקיימות נשמרות מ־V3.</p></div><button class="btn" data-action="add-list">רשימה חדשה</button></div>${state.packing.map(list=>{const done=list.items.filter(i=>i.done).length;return `<section class="card" style="box-shadow:none"><div class="section-head"><h3>${esc(list.name)}</h3><span class="badge">${done}/${list.items.length}</span></div><div class="progress"><span style="width:${list.items.length?done/list.items.length*100:0}%"></span></div>${list.items.map(item=>`<label class="check-row ${item.done?'done':''}"><input type="checkbox" data-action="pack-toggle" data-list="${list.id}" data-item="${item.id}" ${item.done?'checked':''}><span>${esc(item.name)} ${item.suggested?'<small class="badge blue">Suggested</small>':''}</span></label>`).join('')}<div class="actions"><button class="btn secondary" data-action="pack-add" data-list="${list.id}">הוספת פריט</button></div></section>`}).join('')}</section>`}

function detail(){const item=state.items.find(i=>i.id===state.itemId);if(!item)return '<section class="card">הפריט לא נמצא.</section>';const sources=state.sources.filter(s=>item.sourceIds?.includes(s.id));return `<section class="card ${conflict(item)?'conflict':''}"><button class="btn ghost" data-route="center" data-cat="${item.type}">חזרה</button><h2>${ITEM_TYPES[item.type]?.icon||'📌'} ${esc(item.title)}</h2><p><span class="badge">${ITEM_TYPES[item.type]?.label}</span></p>${item.provider?`<p><b>ספק:</b> ${esc(item.provider)}</p>`:''}${item.confirmationNumber?`<p><b>מספר הזמנה:</b> ${esc(item.confirmationNumber)}</p>`:''}${item.location?`<p><b>מיקום:</b> ${esc(item.location)}</p>`:''}${item.startAt?`<p><b>מועד:</b> ${fmt(item.startAt)}</p>`:''}${item.endAt?`<p><b>סיום:</b> ${fmt(item.endAt)}</p>`:''}${item.notes?`<p>${esc(item.notes)}</p>`:''}${sources.length?`<h3>מקורות</h3><div class="list">${sources.map(sourceRow).join('')}</div>`:''}<div class="actions"><button class="btn secondary" data-action="edit-item" data-id="${item.id}">עריכה</button><button class="btn danger" data-action="delete-item" data-id="${item.id}">מחיקה</button></div></section>`}
function suggestionView(){const suggestion=suggestionById(state.suggestionId);if(!suggestion)return '<section class="card">ההצעה לא נמצאה.</section>';const source=sourceById(suggestion.sourceId),p=suggestion.proposed;return `<section class="card"><button class="btn ghost" data-route="center" data-cat="document">חזרה</button><div class="section-head"><div><h2>בדיקת הצעה</h2><p class="muted">המידע הוא הצעה בלבד. פריט ייווצר רק לאחר אישור.</p></div><span class="badge ${suggestion.confidence==='low'?'warn':'blue'}">ביטחון ${confidenceLabel(suggestion.confidence)}</span></div><div class="source-summary"><b>מקור:</b> ${esc(source?.name||source?.url||'')}</div>${suggestion.warnings.length?`<div class="warning-list">${suggestion.warnings.map(w=>`<div>⚠️ ${esc(w)}</div>`).join('')}</div>`:''}<form id="suggestion-form" data-id="${suggestion.id}">${proposalFields(p)}<div class="actions"><button class="btn" name="decision" value="approve">אישור ויצירת פריט</button><button class="btn secondary" name="decision" value="save">שמירת עריכה</button><button class="btn ghost" type="button" data-action="defer-suggestion" data-id="${suggestion.id}">אחר כך</button><button class="btn danger" type="button" data-action="reject-suggestion" data-id="${suggestion.id}">דחייה</button></div></form></section>`}
function proposalFields(p){return `<div class="grid two"><div class="field"><label>סוג</label><select name="type">${Object.entries(ITEM_TYPES).filter(([k])=>k!=='document').map(([key,type])=>`<option value="${key}" ${p.type===key?'selected':''}>${type.icon} ${type.label}</option>`).join('')}</select></div><div class="field"><label>כותרת</label><input name="title" required value="${esc(p.title)}"></div><div class="field"><label>ספק</label><input name="provider" value="${esc(p.provider)}"></div><div class="field"><label>מספר הזמנה</label><input name="confirmationNumber" value="${esc(p.confirmationNumber)}"></div><div class="field"><label>מיקום</label><input name="location" value="${esc(p.location)}"></div><div class="field"><label>תאריך התחלה</label><input type="datetime-local" name="startAt" value="${esc(p.startAt)}"></div><div class="field"><label>תאריך סיום</label><input type="datetime-local" name="endAt" value="${esc(p.endAt)}"></div><div class="field"><label>משתתפים</label><input name="participants" value="${esc((p.participants||[]).join(', '))}" placeholder="שמות מופרדים בפסיקים"></div></div><div class="field"><label>הערות</label><textarea name="notes">${esc(p.notes)}</textarea></div>`}
function settings(){if(!state.trip)return empty();return `<section class="card"><h2>הגדרות הטיול</h2><form id="trip-form"><div class="field"><label>שם הטיול</label><input name="name" required value="${esc(state.trip.name)}"></div><div class="grid two"><div class="field"><label>תאריך התחלה</label><input type="date" name="startDate" value="${esc(state.trip.startDate)}"></div><div class="field"><label>תאריך סיום</label><input type="date" name="endDate" value="${esc(state.trip.endDate)}"></div></div><button class="btn">שמירה</button></form></section>`}
function intakeModal(){const source=state.modal?.source||'manual';return `<div class="modal-bg"><section class="modal"><div class="modal-head"><h2>הוספת מקור או פריט</h2><button class="close" data-action="close">✕</button></div><div class="source-choice">${[['manual','✍️ ידני'],['file','📄 PDF / תמונה'],['photo','📷 צילום'],['link','🔗 קישור']].map(([key,label])=>`<button class="${source===key?'active':''}" data-action="source" data-source="${key}">${label}</button>`).join('')}</div>${source==='manual'?`<form id="manual-form">${proposalFields({type:'hotel',title:'',provider:'',confirmationNumber:'',location:'',startAt:state.trip?.startDate?`${state.trip.startDate}T12:00`:'',endAt:'',participants:[],notes:''})}<button class="btn">יצירת פריט</button></form>`:source==='link'?`<div class="field"><label>קישור</label><input id="source-link" type="url" placeholder="https://..."></div><div class="actions"><button class="btn" data-action="ingest">קליטת קישור</button></div>`:`<div class="field"><label>${source==='photo'?'צילום':'קובץ'}</label><input id="source-file" type="file" accept="${source==='photo'?'image/*':'application/pdf,image/*'}" ${source==='photo'?'capture="environment"':''}></div><div class="actions"><button class="btn" data-action="ingest">קליטת מקור</button></div>`}</section></div>`}
function itemEditModal(){const item=state.items.find(i=>i.id===state.modal.itemId);return `<div class="modal-bg"><section class="modal"><div class="modal-head"><h2>עריכת פריט</h2><button class="close" data-action="close">✕</button></div><form id="edit-item-form" data-id="${item.id}">${proposalFields({...item,participants:item.participants||[]})}<button class="btn">שמירת שינויים</button></form></section></div>`}
function duplicateModal(){const {suggestionId,duplicateIds}=state.modal;const suggestion=suggestionById(suggestionId),duplicates=state.items.filter(i=>duplicateIds.includes(i.id));return `<div class="modal-bg"><section class="modal"><div class="modal-head"><h2>נמצאה הזמנה דומה</h2><button class="close" data-action="close">✕</button></div><p>לפני יצירת הפריט בחר כיצד להמשיך.</p><div class="list">${duplicates.map(itemRow).join('')}</div><div class="actions"><button class="btn" data-action="duplicate-merge" data-suggestion="${suggestion.id}" data-target="${duplicates[0]?.id||''}">מיזוג</button><button class="btn secondary" data-action="duplicate-keep" data-suggestion="${suggestion.id}">שמירת שניהם</button><button class="btn ghost" data-action="close">ביטול</button></div></section></div>`}
function modal(){if(!state.modal)return '';if(state.modal.type==='intake')return intakeModal();if(state.modal.type==='edit-item')return itemEditModal();if(state.modal.type==='duplicate')return duplicateModal();return ''}
function nav(){return `<nav class="nav">${[['today','🏠','Today'],['timeline','🗓️','Timeline'],['calendar','📅','Calendar'],['center','🗂️','Trip Center'],['settings','⚙️','הגדרות']].map(([key,icon,label])=>`<button class="${state.view===key||(['detail','suggestion'].includes(state.view)&&key==='center')?'active':''}" data-route="${key}">${icon}<br>${label}</button>`).join('')}</nav>`}
function render(){const body=state.view==='today'?todayView():state.view==='timeline'?timeline():state.view==='calendar'?calendar():state.view==='center'?center():state.view==='detail'?detail():state.view==='suggestion'?suggestionView():state.view==='packing'?packing():state.view==='settings'?settings():todayView();document.querySelector('#app').innerHTML=`<div class="shell">${!navigator.onLine?'<div class="offline">מצב אופליין — המידע המקומי זמין</div>':''}${header()}<main>${body}</main><button class="fab" data-action="create">+</button>${nav()}${modal()}${state.toast?`<div class="toast">${esc(state.toast)}</div>`:''}</div>`}

async function storeOriginal(source,file){
  const db=await openDb();
  await new Promise((resolve,reject)=>{const tx=db.transaction('files','readwrite');tx.objectStore('files').put({id:source.id,blob:file,name:file.name,type:file.type});tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});
  source.storedOffline=true;
}
async function openSource(id){const source=sourceById(id);if(!source)return;if(source.kind==='link'){open(source.url,'_blank','noopener');return}try{const db=await openDb(),record=await new Promise((resolve,reject)=>{const tx=db.transaction('files','readonly'),req=tx.objectStore('files').get(id);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});if(!record?.blob){notify('הקובץ המקורי אינו זמין במכשיר זה');return}const url=URL.createObjectURL(record.blob);open(url,'_blank','noopener');setTimeout(()=>URL.revokeObjectURL(url),60000)}catch(error){console.error(error);notify('פתיחת המקור נכשלה')}}
function openDb(){return new Promise((resolve,reject)=>{const req=indexedDB.open('family-trips-v4',1);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains('files'))req.result.createObjectStore('files',{keyPath:'id'})};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}

async function ingest(){const kind=state.modal.source;if(kind==='link'){const url=document.querySelector('#source-link')?.value.trim();const validation=validateSource({kind,url});if(!validation.ok){alert(validation.error);return}ensureTrip({name:'טיול חדש'});const source={id:uid('src'),kind:'link',url,name:url,status:'ממתין לאישור',createdAt:new Date().toISOString(),storedOffline:true};state.sources.push(source);state.suggestions.push(createSuggestion(source));save();state.modal=null;route('center',{category:'document'});notify('הקישור נקלט כהצעה');return}
  const file=document.querySelector('#source-file')?.files?.[0];const validation=validateSource({kind,file});if(!validation.ok){alert(validation.error);return}ensureTrip({name:'טיול חדש'});const source={id:uid('src'),kind:kind==='photo'?'photo':'file',name:file.name,type:file.type,size:file.size,status:'ממתין לאישור',createdAt:new Date().toISOString(),storedOffline:false};state.sources.push(source);try{await storeOriginal(source,file)}catch(error){console.error(error);source.status='שגיאת שמירת מקור';state.sources=state.sources.filter(s=>s.id!==source.id);alert('שמירת המקור נכשלה. לא נוצרה הצעה.');return}state.suggestions.push(createSuggestion(source));save();state.modal=null;route('center',{category:'document'});notify('המקור נשמר כהצעה וממתין לאישור')}
function updateSuggestionFromForm(form,suggestion){const data=new FormData(form),type=String(data.get('type'));suggestion.proposed={...suggestion.proposed,type,title:String(data.get('title')||'').trim(),provider:String(data.get('provider')||'').trim(),confirmationNumber:String(data.get('confirmationNumber')||'').trim(),location:String(data.get('location')||'').trim(),startAt:String(data.get('startAt')||''),endAt:String(data.get('endAt')||''),participants:String(data.get('participants')||'').split(',').map(v=>v.trim()).filter(Boolean),notes:String(data.get('notes')||'').trim(),schedule:ITEM_TYPES[type]?.schedule||'none'};suggestion.updatedAt=new Date().toISOString();suggestion.status='pending'}
function approveSuggestion(suggestion,mode='check',targetId=''){const duplicates=findPossibleDuplicates(suggestion,state.items);if(mode==='check'&&duplicates.length){state.modal={type:'duplicate',suggestionId:suggestion.id,duplicateIds:duplicates.map(i=>i.id)};render();return}if(mode==='merge'){const target=state.items.find(i=>i.id===targetId);if(!target)return;Object.assign(target,suggestionToItem(suggestion,target))}else state.items.push(suggestionToItem(suggestion));suggestion.status='approved';const source=sourceById(suggestion.sourceId);if(source)source.status='משויך לפריט';save();state.modal=null;route('center',{category:suggestion.proposed.type});notify(mode==='merge'?'ההצעה מוזגה לפריט קיים':'ההצעה אושרה ונוצר פריט')}

addEventListener('click',async event=>{const routeButton=event.target.closest('[data-route]');if(routeButton){route(routeButton.dataset.route,{category:routeButton.dataset.cat,itemId:routeButton.dataset.id,suggestionId:routeButton.dataset.id});return}const button=event.target.closest('[data-action]');if(!button)return;const action=button.dataset.action;if(action==='create'){state.modal={type:'intake',source:'manual'};render()}else if(action==='close'){state.modal=null;render()}else if(action==='source'){state.modal.source=button.dataset.source;render()}else if(action==='ingest'){await ingest()}else if(action==='timeline-mode'){state.timelineMode=button.dataset.mode;render()}else if(action==='calendar-date'){state.calendarDate=button.dataset.date;render()}else if(action==='open-source'){await openSource(button.dataset.id)}else if(action==='defer-suggestion'){const s=suggestionById(button.dataset.id);s.status='deferred';save();route('center',{category:'document'});notify('ההצעה נשמרה לאחר כך')}else if(action==='reject-suggestion'){const s=suggestionById(button.dataset.id);if(confirm('לדחות את ההצעה? המקור המקורי יישמר.')){s.status='rejected';save();route('center',{category:'document'});notify('ההצעה נדחתה והמקור נשמר')}}else if(action==='duplicate-merge'){approveSuggestion(suggestionById(button.dataset.suggestion),'merge',button.dataset.target)}else if(action==='duplicate-keep'){approveSuggestion(suggestionById(button.dataset.suggestion),'keep')}else if(action==='edit-item'){state.modal={type:'edit-item',itemId:button.dataset.id};render()}else if(action==='add-list'){const name=prompt('שם הרשימה');if(name){state.packing.push({id:uid('pl'),name,items:[]});save();render()}}else if(action==='pack-add'){const name=prompt('שם הפריט');if(name){const list=state.packing.find(l=>l.id===button.dataset.list);list.items.push({id:uid('pi'),name,done:false,suggested:false});save();render()}}else if(action==='delete-item'){if(confirm('למחוק את הפריט? המקורות יחזרו למסמכים.')){const item=state.items.find(i=>i.id===button.dataset.id);for(const sourceId of item?.sourceIds||[]){const source=sourceById(sourceId);if(source)source.status='לא משויך'}state.items=state.items.filter(i=>i.id!==button.dataset.id);save();route('center');notify('הפריט נמחק והמקורות נשמרו')}}});

addEventListener('submit',event=>{event.preventDefault();if(event.target.id==='trip-form'){const data=new FormData(event.target),start=String(data.get('startDate')||''),end=String(data.get('endDate')||'');if(start&&end&&start>end){alert('תאריך הסיום חייב להיות אחרי תאריך ההתחלה');return}state.trip={...state.trip,name:String(data.get('name')).trim(),startDate:start,endDate:end};save();render();notify('הטיול נשמר')}else if(event.target.id==='manual-form'){const data=new FormData(event.target),type=String(data.get('type'));ensureTrip();state.items.push({id:uid('item'),type,title:String(data.get('title')||'').trim(),provider:String(data.get('provider')||'').trim(),confirmationNumber:String(data.get('confirmationNumber')||'').trim(),location:String(data.get('location')||'').trim(),startAt:String(data.get('startAt')||''),endAt:String(data.get('endAt')||''),participants:String(data.get('participants')||'').split(',').map(v=>v.trim()).filter(Boolean),notes:String(data.get('notes')||'').trim(),schedule:ITEM_TYPES[type]?.schedule||'none',sourceIds:[],updatedAt:new Date().toISOString()});save();state.modal=null;route('center',{category:type});notify('הפריט נוצר')}else if(event.target.id==='edit-item-form'){const item=state.items.find(i=>i.id===event.target.dataset.id),data=new FormData(event.target),type=String(data.get('type'));Object.assign(item,{type,title:String(data.get('title')||'').trim(),provider:String(data.get('provider')||'').trim(),confirmationNumber:String(data.get('confirmationNumber')||'').trim(),location:String(data.get('location')||'').trim(),startAt:String(data.get('startAt')||''),endAt:String(data.get('endAt')||''),participants:String(data.get('participants')||'').split(',').map(v=>v.trim()).filter(Boolean),notes:String(data.get('notes')||'').trim(),schedule:ITEM_TYPES[type]?.schedule||'none',updatedAt:new Date().toISOString()});save();state.modal=null;route('detail',{itemId:item.id});notify('הפריט עודכן')}else if(event.target.id==='suggestion-form'){const suggestion=suggestionById(event.target.dataset.id);updateSuggestionFromForm(event.target,suggestion);const decision=event.submitter?.value;if(decision==='approve'){save();approveSuggestion(suggestion)}else{save();render();notify('עריכת ההצעה נשמרה')}}});
addEventListener('online',render);addEventListener('offline',render);render();

addEventListener('change',event=>{if(event.target.dataset.action==='pack-toggle'){const list=state.packing.find(l=>l.id===event.target.dataset.list),item=list?.items.find(i=>i.id===event.target.dataset.item);if(item){item.done=event.target.checked;save();render()}}});
